name: Flutter Web CI/CD Deployment

# Triggers the workflow on pushes to the main branch
on:
  push:
    branches: [ master ]
  # Allows manual triggering from the GitHub Actions tab
  workflow_dispatch:

permissions:
  contents: write   # allow creating/updating Releases & uploading assets
  actions:  read 

jobs:
  build_and_release:
    permissions:
      contents: write # Grants the necessary permission for peaceiris/actions-gh-pages to push

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /portfolio/
          webRenderer: canvaskit